apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LubnaIbrahimMU/wordpress-container.git
    targetRevision: helm
    path: wordpress
    # helm:
    #   valueFiles:
    #     - values.yaml
    # Reference the secret for accessing the private repo
    repoCreds:
      secretName: argocd-repo-creds
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # imagePullSecrets:
  #   - name: regcred


# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: wordpress
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/LubnaIbrahimMU/wordpress-container.git
#     targetRevision: kustomize
#     path: k8s
#     helm:
#       valueFiles:
#         - values.yaml
#     # Reference the secret for accessing the private repo
#     repoCreds:
#       secretName: argocd-repo-creds
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: wordpress
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true