apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
type: Opaque
data:
  docker.config: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJsdWJuYWlicmFoaW11IiwicGFzc3dvcmQiOiJkY2tyX3BhdF9tT1JUYUE2Sy1iRlEtOFdiTkpvU01TRWZfR0UiLCJlbWFpbCI6Imx1Ym5haWJyYWhpbTAwMEBnbWFpbC5jb20iLCJhdXRoIjoiYkhWaWJtRnBZbkpoYUdsdGRUcGtZMnR5WDNCaGRGOXRUMUpVWVVFMlN5MWlSbEV0T0ZkaVRrcHZVMDFUUldaZlIwVT0ifX19
