# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-pass
# type: Opaque
# data:
#   MYSQL_ROOT_PASSWORD: cGFzc0AxMjM=

apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc0AxMjM=
  password: cGFzc0AxMjM=   # Same value as MYSQL_ROOT_PASSWORD


