name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get short commit hash
        id: vars
        run: echo "::set-output name=short_commit_hash::$(git rev-parse --short HEAD)"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lu1-wordpress:${{ steps.vars.outputs.short_commit_hash }}

      - name: Checkout Helm branch
        run: git checkout helm

      - name: Print values.yaml before update
        run: cat wordpress/values.yaml

      - name: Print wordpress.yaml before update
        run: cat kustomize/k8s/kustomization.yaml

      - name: Update values.yaml
        run: |
          sed -i "s|tag:.*|tag: ${{ steps.vars.outputs.short_commit_hash }}|g" wordpress/values.yaml

      - name: Update deploy.yaml
        run: |
          sed -i "s|newTag: .*|newTag: ${{ steps.vars.outputs.short_commit_hash }}|g" kustomize/k8s/kustomization.yaml

      - name: Print values.yaml after update
        run: cat wordpress/values.yaml

      - name: Print wordpress.yaml before update
        run: cat kustomize/k8s/kustomization.yaml

      - name: Commit updated values.yaml
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add wordpress/values.yaml
          git commit -m "Update image tag to ${{ steps.vars.outputs.short_commit_hash }}"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin helm


